config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'

  resources :responsibilities do
    member do
      get :complete
    end
  end
  resources :journals
  resources :timeblocks
  resources :goals
  resources :user_profile, controller: 'user_profile'

  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/responsibility.rb
class Responsibility < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable #, :registerable

  has_many :responsibilities
  has_many :journals
  has_many :goals

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: ["100x100#"] }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :authenticate_user!
  def index
    @user = current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:destroy, :edit, :update, :show]
  def index
    @goals = current_user.goals
  end

  def new
    @goal = current_user.goals.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save!
      redirect_to goal_params, notice: 'Journal Created Successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to goals_path, notice: 'Journal Updated Successfully!'
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_path, notice: 'Journal Deleted Successfully!'
  end

  def show
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :deadline)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:destroy, :edit, :update, :show]
  def index
    @journals = current_user.journals
  end

  def new
    @journal = current_user.journals.new
  end

  def create
    @journal = current_user.journals.new(journal_params)
    if @journal.save!
      redirect_to journal_params, notice: 'Journal Created Successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @journal.update(journal_params)
      redirect_to journals_path, notice: 'Journal Updated Successfully!'
    else
      render :edit
    end
  end

  def destroy
    @journal.destroy
    redirect_to journals_path, notice: 'Journal Deleted Successfully!'
  end

  def show
  end

  private

  def set_journal
    @journal = Journal.find(params[:id])
  end

  def journal_params
    params.require(:journal).permit(:cause, :effect, :feeling)
  end

end

app/controllers/responsibilities_controller.rb
class ResponsibilitiesController < ApplicationController
  before_action :set_responsibility, only: [:destroy, :edit, :update, :show, :complete]
  def index
    @responsibilities = current_user.responsibilities
    @completed_responsibilities = current_user.responsibilities.where(status: 'Completed')
    @incomplete_responsibilities = current_user.responsibilities.where.not(status: 'Completed')
  end

  def new
    @responsibility = current_user.responsibilities.new
    @responsibility.status = 'New'
  end

  def create
    @responsibility = current_user.responsibilities.new(responsibility_params)
    if @responsibility.save!
      redirect_to responsibilities_path, notice: 'Responsibility Created Successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @responsibility.update(responsibility_params)
      redirect_to responsibilities_path, notice: 'Responsibility Updated Successfully!'
    else
      render :edit
    end
  end

  def complete
    @responsibility.update(status: 'Completed')
    redirect_to responsibilities_path, notice: 'Responsibility Completed!'
  end

  def destroy
    @responsibility.destroy
    redirect_to responsibilities_path, notice: 'Responsibility Deleted Successfully!'
  end

  def show
  end

  private

  def set_responsibility
    @responsibility = Responsibility.find(params[:id])
  end

  def responsibility_params
    params.require(:responsibility).permit(:name, :details, :status, :start_date, :deadline)
  end



end

app/controllers/timeblocks_controller.rb
class TimeblocksController < ApplicationController
  def index
    @total_blocks = 144
  end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_profile_path, notice: 'User Updated Successfully!'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
  <h1>Welcome <%= @user.email %>!</h1>
<% else %>
  <h1>Hello, welcome to assisty!</h1>
  <p>Sign in to start improving your life!</p>
  <p>Or contact us @ spclight@gmail.com</p>
<% end %>

app/views/goals/_form.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Goal details</span>
        <%= simple_form_for @goal do |f| %>
            <%= f.input :title%>
            <%= f.text_field :deadline, class: 'datepicker', placeholder: 'Achieve By'%>
            <div class="card-action">
              <%= link_to 'back', :back %>
              <%= f.button :submit, class: 'right' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<%= render partial: 'form', locals: { goal: @goal } %>

app/views/goals/index.html.erb
<h1>Goals</h1>
<% count = 1 %>
<% @goals.each_with_index do |goal, i| %>
    <div class="card">
      <div class="card-content">
        <div class="card-title"><%= count.to_s + '. ' + goal.title.titleize%></div>
        <span><h5>Achieve By</h5><%= goal.deadline %></span>
        <div class="right-align">
          <%= link_to 'Show', goal, class: 'waves-effect waves-light btn' %>
          <%= link_to 'Edit', edit_goal_path(goal), class: 'waves-effect waves-light btn' %>
          <a class="waves-effect waves-light btn modal-trigger" href="#goal-delete-modal-<%= i %>" data-turbolinks="false">Delete</a>
        </div>
      </div>
    </div>
    <% count += 1 %>
    <div id="goal-delete-modal-<%= i %>" class="modal">
      <div class="modal-content">
        <h4>Are you sure?</h4>
        <p>This action cannot be undone.</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Yes', goal, method: :delete, class: 'modal-action modal-close waves-effect waves-light btn' %>
        <button class="modal-action modal-close waves-effect waves-green btn-flat">No</button>
      </div>
    </div>
<% end %>
<div class="fixed-action-btn">
  <%= link_to(new_goal_path, class: 'btn-floating btn-large') do %>
      <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/goals/new.html.erb
<%= render partial: 'form', locals: { goal: @goal }  %>

app/views/goals/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-title"><%= @goal.title %></div>
    <span><h5>Achieve By: </h5><%= @goal.deadline %></span>
  </div>
  <div class="card-action">
    <%= link_to 'back', :back %>
  </div>
</div>

app/views/journals/_form.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Journal details</span>
        <%= simple_form_for @journal do |f| %>
            <%= f.input :cause, :label => "What happened today?"%>
            <%= f.input :effect, :label => "How are you related to it?"%>
            <%= f.input :feeling, :label => "How did you feel?"%>
          <div class="card-action">
            <%= link_to 'back', :back %>
            <%= f.button :submit, class: 'right' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journals/edit.html.erb
<%= render partial: 'form', locals: { journal: @journal } %>

app/views/journals/index.html.erb
<h1>Journals</h1>
<% count = 1 %>
<% @journals.each_with_index do |journal, i| %>
    <div class="card">
      <div class="card-content">
        <div class="card-title">#<%= count %></div>
        <div class="card-title right-align"><%= journal.created_at.strftime('%A, %B %d, %Y') %></div>
        <span><h5>What happened today?</h5><%= journal.cause.truncate_words(10) %></span>
        <span><h5>How are you related to it?</h5><%= journal.effect.truncate_words(10) %></span>
        <span><h5>How did you feel?</h5><%= journal.feeling.truncate_words(10) %></span>
        <div class="right-align">
          <%= link_to 'Show', journal, class: 'waves-effect waves-light btn' %>
          <%= link_to 'Edit', edit_journal_path(journal), class: 'waves-effect waves-light btn' %>
          <a class="waves-effect waves-light btn modal-trigger" href="#journal-delete-modal-<%= i %>" data-turbolinks="false">Delete</a>
        </div>
      </div>
    </div>
    <% count += 1 %>
    <div id="journal-delete-modal-<%= i %>" class="modal">
      <div class="modal-content">
        <h4>Are you sure?</h4>
        <p>This action cannot be undone.</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Yes', journal, method: :delete, class: 'modal-action modal-close waves-effect waves-light btn' %>
        <button class="modal-action modal-close waves-effect waves-green btn-flat">No</button>
      </div>
    </div>
<% end %>

<div class="fixed-action-btn">
  <%= link_to(new_journal_path, class: 'btn-floating btn-large') do %>
    <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/journals/new.html.erb
<%= render partial: 'form', locals: { journal: @journal }  %>

app/views/journals/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-title right-align"><%= @journal.created_at.strftime('%A, %B %d, %Y') %></div>
    <span><h5>What happened today?</h5><%= @journal.cause %></span>
    <span><h5>How are you related to it?</h5><%= @journal.effect %></span>
    <span><h5>How did you feel?</h5><%= @journal.feeling %></span>
  </div>
  <div class="card-action">
    <%= link_to 'back', :back %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResponsibilityRails</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo left">
      <%= image_tag('app_logo_white.png') %>
    </a>
      <a href="#" data-activates="slide-out" class="button-collapse right hide-on-large-only show-on-medium-and-down"><i class="material-icons right">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
            <li><%= link_to 'Profile', user_profile_path(current_user), class: 'waves-effect' %></li>
            <li><%= link_to 'Goals', goals_path, class: 'waves-effect' %></li>
            <li><%= link_to 'Pomodoro', timeblocks_path, class: 'waves-effect' %></li>
            <li><%= link_to 'Journals', journals_path, class: 'waves-effect' %></li>
            <li><%= link_to 'Responsibilities', responsibilities_path, class: 'waves-effect' %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'waves-effect' %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

<ul id="slide-out" class="side-nav">
  <% if user_signed_in? %>
    <li>
      <div class="user-view">
        <div class="background">
          <%= image_tag('app_logo.png') %>
        </div>
        <a href="#!user">
          <!--<img class="circle" src="images/yuna.jpg">-->
          Profile Pict
        </a>
        <a href="#!name"><span class="white-text name">Username</span></a>
        <a href="#!email"><span class="white-text email">Email</span></a>
      </div>
    </li>
    <li>
      <%=link_to(user_profile_path(current_user), class: 'waves-effect') do %>
        <i class="material-icons">cloud</i>Profile
      <% end %>
    </li>
    <li>
      <%= link_to(responsibilities_path, class: 'waves-effect') do %>
        <i class="material-icons">cloud</i>Responsibilities
      <% end %>
    </li>
    <li>
      <%= link_to(journals_path, class: 'waves-effect') do %>
        <i class="material-icons">book</i>Journal
      <% end %>
    </li>
    <li>
      <%= link_to(goals_path, class: 'waves-effect') do %>
        <i class="material-icons">book</i>Goal
      <% end %>
    </li>
    <li>
      <%= link_to(timeblocks_path, class: 'waves-effect') do %>
        <i class="material-icons">access_time</i>Pomodoro
      <% end %>
    </li>
    <li>
      <div class="divider"></div>
    </li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'waves-effect' %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
</ul>
<p class="notice"><%= notice %></p>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/responsibilities/_form.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Responsbility details</span>
        <%= simple_form_for @responsibility do |f| %>
            <%= f.input :name %>
            <%= f.input :details %>
            <%= f.input :status %>
            <%= f.text_field :start_date, class: 'datepicker', placeholder: 'Start Date' %>
            <%= f.text_field :deadline, class: 'datepicker', placeholder: 'End Date' %>
            <%= f.button :submit %>
        <% end %>
      </div>
    </div>
    <div class="card-action">
      <%= link_to 'back', :back %>
    </div>
  </div>
</div>

app/views/responsibilities/_item.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title"><%= count.to_s + '. ' + responsibility.name.titleize %></span><br>
    <%= responsibility.details %>
    <div class="right-align">
      <%= link_to 'Show', responsibility, class: 'waves-effect waves-light btn' %>
      <% unless responsibility.status == 'Completed' %>
        <%= link_to 'Complete', complete_responsibility_path(responsibility), class: 'waves-effect waves-light btn' %>
      <% end %>
      <%= link_to 'Edit', edit_responsibility_path(responsibility), class: 'waves-effect waves-light btn' %>
      <a class="waves-effect waves-light btn modal-trigger" href="#responsibility-delete-modal-<%= i %>" data-turbolinks="false">Delete</a>
    </div>
  </div>
</div>
<div id="responsibility-delete-modal-<%= i %>" class="modal">
  <div class="modal-content">
    <h4>Are you sure?</h4>
    <p>Have you fulfilled your responsibility?</p>
  </div>
  <div class="modal-footer">
    <%= link_to 'Yes', responsibility, method: :delete, class: 'modal-action modal-close waves-effect waves-light btn' %>
    <button class="modal-action modal-close waves-effect waves-green btn-flat">No</button>
  </div>
</div>

app/views/responsibilities/edit.html.erb
<%= render partial: 'form', locals: { responsibility: @responsibility } %>

app/views/responsibilities/index.html.erb
<h1>Responsibilities</h1>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#incomplete-responsibility-tab">Incomplete</a></li>
      <li class="tab col s3"><a href="#completed-responsibility-tab">Completed</a></li>
    </ul>
    <div id="incomplete-responsibility-tab" class="col s12">
      <% count = 1 %>
      <% @incomplete_responsibilities.each_with_index do |responsibility, i| %>
        <%= render partial: 'item', locals: {responsibility: responsibility, i: i, count: count} %>
        <% count += 1 %>
      <% end %>
    </div>
    <div id="completed-responsibility-tab" class="col s12">
      <% count = 1 %>
      <% @completed_responsibilities.each_with_index do |responsibility, i| %>
        <%= render partial: 'item', locals: {responsibility: responsibility, i: i, count: count} %>
        <% count += 1 %>
      <% end %>
    </div>
  </div>
</div>

<div class="fixed-action-btn">
  <%= link_to(new_responsibility_path, class: 'btn-floating btn-large') do %>
    <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/responsibilities/new.html.erb
<%= render partial: 'form', locals: { responsibility: @responsibility }  %>

app/views/responsibilities/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-title"><%= @responsibility.name.titleize %></div>
    <div>Details: <%= @responsibility.details.to_s %></div>
    <div>Status: <%= @responsibility.status %></div>
    <div>Start: <%= @responsibility.start_date&.to_date %></div>
    <div>Deadline: <%= @responsibility.deadline&.to_date %>  </div>
  </div>
  <div class="card-action">
    <%= link_to 'back', :back %>
  </div>
</div>

app/views/timeblocks/index.html.erb
<h1>Pomodoro</h1>
<!--<div class="waves-effect waves-light btn " id= "startClock">START</div>-->
<!--<div class="waves-effect red lighten-1 btn">PAUSE</div>-->
<h4 id="pomodoro-timer"></h4>
<div>
  <% @total_blocks.times do |block| %>
    <div id="time-block-<%= block.to_s %>" class="time-block red" style="height: 0px;">
    </div>
  <% end %>
</div>

app/views/user_profile/edit.html.erb
<h1>Update Profile</h1>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-content">
        <span class="card-title">User details</span>
        <%= simple_form_for @user, url: user_profile_path do |f| %>
          <%= f.input :firstname %>
          <%= f.input :lastname %>
          <%= f.input :email %>
          <%= f.input :avatar, as: :file %>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
    <!--<div class="card-action">-->
      <!--<#% link_to 'back', :back %>-->
    <!--</div>-->
  </div>
</div>

app/views/user_profile/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-title"><%= @user.firstname.to_s + ' ' + @user.lastname.to_s %></div>
    <div><%= @user.email.to_s %></div>

    <%#= image_tag @user.avatar.url %>
    <%#= image_tag @user.avatar.url(:medium) %>
    <%= image_tag @user.avatar.url(:thumb) %>

    <div class="right-align">
      <%= link_to 'Edit', edit_user_profile_path(@user), class: 'waves-effect waves-light btn' %>
    </div>

  </div>
</div>